name: Repository Dispatch
on:
  repository_dispatch:
    types: [bookkeeping_app-release]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bookkeeping app
        uses: actions/checkout@v2
        with:
          repository: hemanta212/notekeeping_app
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          ref: ${{ github.event.client_payload.ref }}
          path: 'app'

      - run: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
      - run: echo ::add-path::`pwd`"/flutter/bin"

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - run: |
          cd app
          flutter pub get
          flutter build apk
          mkdir build/app/outputs/apk/app_release && mv build/app/outputs/apk/release/*.apk build/app/outputs/apk/app_release/
          flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app/build/app/outputs/apk/release/app-arm64-v8a-release.apk
            app/build/app/outputs/apk/release/app-armeabi-v7a-release.apk
            app/build/app/outputs/apk/release/app-x86_64-release.apk
            app/build/app/outputs/apk/app_release/app-release.apk
          body_path: app/CHANGELOG.txt
          tag_name: ${{ github.event.client_payload.ref }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
