on:
  push:

name: Run Build
jobs:
  linux:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - run: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
      - run: echo ::add-path::`pwd`"/flutter/bin"

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: actions/checkout@v2
        with:
          path: 'app'

      - run: |
          cd app/simple_interest_calculator
          flutter pub get
          flutter build apk
          cd ../notekeeping_app/
          flutter pub get
          flutter build apk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            app/simple_interest_calculator/build/app/outputs/apk/app_release/app-release.apk
            app/notekeeping_app/build/app/outputs/apk/app_release/app-release.apk
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
