name: Build
on:
  push:


jobs:
  setup:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       project: ['lucky_no_generator', 'hello_world', 'si_calculator', 'notekeeping_app']

   steps:
     - run: |
          git clone https://github.com/flutter/flutter.git
          cd flutter
     - run: echo ::add-path::`pwd`"/flutter/bin"
     - uses: actions/setup-java@v1
       with:
         java-version: '12.x'

     - uses: actions/checkout@v2
       with:
         path: 'app'

     - run: |
          cd app/${{ matrix.project}}
          flutter pub get
          flutter build apk
          mkdir rel
          mv build/app/outputs/apk/release/app-release.apk rel/${{ matrix.project }}-release.apk

     - uses: actions/upload-artifact@v1
       with:
         name: ${{ matrix.project }}-release.apk
         path: app/${{ matrix.project }}/rel/${{ matrix.project }}-release.apk

  release:
    needs: setup
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
         path: 'app'

     - run: |
         cd app
         mkdir rel/

     - uses: actions/download-artifact@v1
       with:
         name: lucky_no_generator-release.apk
         path: rel/

     - uses: actions/download-artifact@v1
       with:
         name: hello_world-release.apk
         path: rel/

     - uses: actions/download-artifact@v1
       with:
         name: notekeeping_app-release.apk
         path: rel/

     - uses: actions/download-artifact@v1
       with:
         name: si_calculator-release.apk
         path: rel/

     - name: Release
       uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
       with:
         files: |
             rel/si_calculator-release.apk
             rel/notekeeping_app-release.apk
             rel/hello_world-release.apk
             rel/lucky_no_generator-release.apk
         body_path: app/CHANGELOG.txt
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
